version: '3.8'
services:
    mysql-db:
      image: mysql:8.0
      container_name: "mysql-db"
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      env_file: ./.env
      environment:
        MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
        MYSQL_DATABASE: $MYSQLDB_DATABASE
      ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
      volumes:
        - db-data:/var/lib/mysql
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 3
    backend:
      container_name: "backend"
      build:
        context: ./short-link-api
        dockerfile: Dockerfile
      volumes:
        - .:/backend
        - /backend/node_modules
      env_file: ./.env
      ports:
        - $NESTJS_APP_LOCAL_PORT:$NESTJS_APP_DOCKER_PORT
      depends_on:
        mysql-db:
          condition: service_healthy
      environment:
        DB_HOST: $MYSQLDB_HOST
        DB_PORT: $MYSQLDB_DOCKER_PORT
        DB_USER: $MYSQLDB_USER
        DB_PASSWORD: $MYSQLDB_PASSWORD
        DB_DATABASE: $MYSQLDB_DATABASE
      command: sh -c "npm run migration:run && npm run start"
    frontend:
      container_name: "frontend"
      build:
        context: ./short-link-web
        dockerfile: Dockerfile
      volumes:
        - .:/frontend
        - /frontend/node_modules
      env_file: ./.env
      environment:
        NEXT_PUBLIC_API_URL: http://backend:3001
      ports:
        - $NEXTJS_APP_LOCAL_PORT:$NEXTJS_APP_DOCKER_PORT
      depends_on:
        - backend
volumes:
  db-data: